### ISSUE TITLE
commit_batch_upload issue

### ISSUE THREAD

**Issue by yafimski** [GRAPHISOFT/bimcloud-api#10]
Hi,
Trying to execute `upload_file()` file by file, but it still requires `commit_batch_upload()` I think, right?:

```
blob_server_api.commit_upload(blob_server_session_id, upload['id'])
blob_server_api.commit_batch_upload(blob_server_session_id, batch['id'])
print(f'File uploaded as "{blob_server_file_path}".')
```

otherwise it will say that it was uploaded, but no actual file appears in the server.
how best to upload files one by one in a loop instead of batch? is there a simpler way other than the `do_upload()` function...?

The terminal output I get when trying with `commit_batch_upload()` is:
> Configured host Blob Server: "Server-2021-02-22".
> <Response [200]>
> Uploading data ...
> <Response [200]>
> <Response [200]>
> <Response [200]>
> <Response [200]>
> <Response [200]>
> <Response [200]>
> <Response [200]>
> <Response [200]>
> <Response [430]>
> Failed to execute request: 'blob-store-service-commit-batch-upload'. Error: 'Batch upload commit failed'.

**Comment by yafimski** [comment]
@unbornchikken 

Been playing around endlessly trying to figure out what is wrong.
I think there is an issue with the `get_resources_by_criterion()` method and its `result`.

In the demo.py, I can get a flow of print outputs through my code debugging (I replaced sensitive info with <>):
```
UPLOAD FILE PATH: Project Root/TEST_PROJECT/Test_2
PATH: Project Root/TEST_PROJECT/Test_2
FILE PATH: C:\Users\...\...\...\bimcloud-api\blobs\text1.txt
PATH / ALIAS: Project Root/TEST_PROJECT/Test_2/text1.txt
SESSION ID: <valid-guid>
session / path: <valid-guid> / Project Root/TEST_PROJECT/Test_2
<><><><><> PARAMS / URL: {'session-id': '<valid-guid>'} / http://<myIP>:22000/management/client/get-resources-by-criterion
><><><><>< RESULT: [**{'$hidden': False, '$visibility': 'full', 'name': 'Test_2', ..... rest of valid result object .... }**]
```

while the same exact experiment with my own local folders and files being uploaded gives:
```
UPLOAD FILE PATH: Project_Root/TEST_PROJECT/Housing_Project
PATH: Project_Root/TEST_PROJECT/Housing_Project
FILE PATH: C:\Users\...\...\...\Housing_Project\test.txt
PATH / ALIAS: Project_Root/TEST_PROJECT/Housing_Project/test.txt
SESSION ID: <valid-guid>
session / path: <valid-guid> / Project_Root/TEST_PROJECT/Housing_Project
<><><><><> PARAMS / URL: {'session-id': '<valid-guid>'} / http://<myIP>:22000/management/client/get-resources-by-criterion
><><><><>< RESULT: [ **invalid, empty result object** ]
```

In demo.py, the result object is valid, in my own experiment, the result object is an empty array.
What could be the issue? 
From my investigation, could be that some api endpoint is not being updated properly or not in time, could this be it? any suggestions on how to further debug or solve?

Thanks

**Comment by unbornchikken** [comment]
It will take some time to uploads getting processed to be able to get the correct result from get-by-criterion. But that's just a few seconds. Maybe the user doesn't have enough rights to see the uploaded content.

**Comment by yafimski** [comment]
solved it in the end with some path string manipulation. it wasn't reading it correctly when passed.
Thanks
