### ISSUE TITLE
create_session() error

### ISSUE THREAD

**Issue by yafimski** [GRAPHISOFT/bimcloud-api#8]
Hi!
I'm using valid credentials to try and access the session at an address h`ttp://<IP address>:22000/#module:project-manager`:

I use my credentials to create an instance of the Workflow class and the ManagerApi class like so:
```
wf = Workflow(server_path, username, password, client_id, main_folder)
wf.login()
manager = wf._manager_api
session = manager.create_session(username, password, client_id)
```

but in create_session() _[in the login part]_ it is failing on the line:
`result = self.process_response(response)`

If I try to go to the `manager._api_root` address directly in my browser, it's an invalid address, so perhaps something is wrong with the initialization of the Manager? 

Thank you

**Comment by yafimski** [comment]
I will also add that I tried running the demo.py and it's failing as well. Did something change in the api? Seems like it's not functional.
The demo.py worked previously (about a week ago) and now that I am trying to run it with the same command from the terminal, just to test, it's failing.

**Comment by unbornchikken** [comment]
Nope, api and the docs has not changed in years, and it's been working perfectly for everyone else. When you say failing what is the raised exception?

**Comment by yafimski** [comment]
Thanks for the reply :)
There are a few aspects here:

I am trying with:
`python ./demo.py -m=<myHttpAddress> -u=YAFIM -p=<myPassword> -clientid=<myDomainString>`

When running the command in a Windows Terminal, first I get an error that:

> At line:1 char:72
+ ... mo.py -m=http://.../#module:project-manager&id:98e82 ...
+                                                                               ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

When I am running it with "" around the &, I get:
> Login as YAFIM ...
HttpErrror: status=404. <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /</pre>
</body>
</html>
.


The online website login to the BIMcloud works, and I can upload files there. 
Domain doesn't matter right? can be random each time? I tried of course with the original one I had the first time this command worked in the terminal (some weeks ago).

I believe the error is within the login() function of the` lib.Workflow `because that's the first time a `create_session()` is attempted and the failure is on that result = self.process_response(response)

**Comment by unbornchikken** [comment]
That's because your BIMcloud url is just https://yourdomain:22000, you should not include random trash to server url.

**Comment by yafimski** [comment]
it's the IP address.. shouldn't it be `http://myIPaddress:22000` ? what should it be do you have an example..?

**Comment by unbornchikken** [comment]
> At line:1 char:72
>  ... mo.py -m=http://.../#module:project-manager&id:98e82 ...
>                                                                                ~
> The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
> quotation marks ("&") to pass it as part of a string.
>      CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>      FullyQualifiedErrorId : AmpersandNotAllowed
> 

It's in the error. You have used:

-m=http://IP:22000/#nodule-etcetc

Instead of just:

-m&http://IP:22000
